# Generated by Django 5.0.6 on 2024-07-10 16:42

import core.directors.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('director_photo', models.ImageField(null=True, upload_to=core.directors.models.director_image_path)),
                ('nationality', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
