# Generated by Django 5.0.6 on 2024-06-22 05:46

import core.movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('Plot', models.TextField(blank=True, max_length=300)),
                ('released_year', models.DateField()),
                ('movie_length', models.IntegerField()),
                ('poster', models.ImageField(blank=True, upload_to=core.movies.models.movie_image_file_path)),
            ],
        ),
    ]
