# Generated by Django 5.0.6 on 2024-07-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_actors', '0001_initial'),
        ('core_directors', '0001_initial'),
        ('core_genres', '0001_initial'),
        ('core_movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='core_actors.actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='movies', to='core_directors.director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='core_genres.genre'),
        ),
    ]
